import 'package:hive/hive.dart';

part 'meal_plan_model.g.dart'; // This will be generated by Hive

@HiveType(typeId: 2) // Define the type ID for Hive
class MealPlanModel extends HiveObject {
  @HiveField(0)
  String day;

  @HiveField(1)
  String meal;

  MealPlanModel({required this.day, required this.meal});
}
